import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

console.log('🚀 Starting build setup...');

try {
  // Check if Sharp is available
  let sharpAvailable = false;
  try {
    require.resolve('sharp');
    sharpAvailable = true;
    console.log('✅ Sharp is available');
  } catch (error) {
    console.log('⚠️  Sharp not available, skipping image optimization');
  }

  // Generate PWA icons (only if Sharp is available)
  if (sharpAvailable) {
    console.log('🎨 Generating PWA icons...');
    try {
      execSync('node generate-pwa-icons.mjs', { stdio: 'inherit' });
    } catch (error) {
      console.log('⚠️  PWA icon generation failed, continuing...');
    }
  } else {
    console.log('⚠️  Skipping PWA icon generation (Sharp not available)');
  }

  // Convert images to WebP (only if Sharp is available)
  if (sharpAvailable) {
    console.log('🖼️ Converting images to WebP...');
    try {
      execSync('node convert-to-webp.mjs', { stdio: 'inherit' });
    } catch (error) {
      console.log('⚠️  WebP conversion failed, continuing...');
    }
  } else {
    console.log('⚠️  Skipping WebP conversion (Sharp not available)');
  }

  // Check if all required files exist
  const requiredFiles = [
    'public/manifest.json',
    'public/sw.js'
  ];

  const optionalFiles = [
    'public/icon-192x192.png',
    'public/icon-512x512.png',
    'public/apple-touch-icon.png',
    'public/favicon.ico',
    'public/favicon.svg'
  ];

  console.log('🔍 Verifying PWA files...');
  for (const file of requiredFiles) {
    const filePath = path.join(__dirname, '..', file);
    if (fs.existsSync(filePath)) {
      console.log(`✅ ${file} exists`);
    } else {
      console.log(`⚠️ ${file} missing`);
    }
  }

  console.log('🔍 Checking optional files...');
  for (const file of optionalFiles) {
    const filePath = path.join(__dirname, '..', file);
    if (fs.existsSync(filePath)) {
      console.log(`✅ ${file} exists`);
    } else {
      console.log(`⚠️ ${file} missing (will be generated by Next.js if needed)`);
    }
  }

  console.log('🎉 Build setup completed successfully!');
  console.log('📱 PWA is ready for installation');
  console.log('🖼️ Images optimized for fast loading');

} catch (error) {
  console.error('❌ Build setup failed:', error.message);
  process.exit(1);
}
